### ISSUE TITLE
not able to install poppler in centos

### ISSUE THREAD

**Issue by karthiklin** [danigm/poppler#1]
The below error occured in compilation time

checking for LIBOPENJPEG... no
configure: error: Package requirements (libopenjp2) were not met:

No package 'libopenjp2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBOPENJPEG_CFLAGS
and LIBOPENJPEG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

[root@x.x.x.x~]# find /usr | grep openj
/usr/share/applications/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64-policytool.desktop
/usr/share/man/man1/openjade.1.gz
/usr/share/man/man1/keytool-java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64.1.gz
/usr/share/man/man1/java-java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64.1.gz
/usr/share/man/man1/jjs-java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64.1.gz
/usr/share/man/man1/rmid-java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64.1.gz
/usr/share/man/man1/servertool-java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64.1.gz
/usr/share/man/man1/tnameserv-java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64.1.gz
/usr/share/man/man1/pack200-java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64.1.gz
/usr/share/man/man1/rmiregistry-java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64.1.gz
/usr/share/man/man1/orbd-java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64.1.gz
/usr/share/man/man1/unpack200-java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64.1.gz
/usr/share/sgml/openjade-1.3.2
/usr/share/sgml/openjade-1.3.2/style-sheet.dtd
/usr/share/sgml/openjade-1.3.2/builtins.dsl
/usr/share/sgml/openjade-1.3.2/catalog
/usr/share/sgml/openjade-1.3.2/dsssl.dtd
/usr/share/sgml/openjade-1.3.2/fot.dtd
/usr/share/doc/java-1.8.0-openjdk-headless-1.8.0.45
/usr/share/doc/java-1.8.0-openjdk-headless-1.8.0.45/ASSEMBLY_EXCEPTION
/usr/share/doc/java-1.8.0-openjdk-headless-1.8.0.45/LICENSE
/usr/share/doc/java-1.8.0-openjdk-headless-1.8.0.45/THIRD_PARTY_README
/usr/share/doc/openjade-1.3.2
/usr/share/doc/openjade-1.3.2/rtf.htm
/usr/share/doc/openjade-1.3.2/autoconf.htm
/usr/share/doc/openjade-1.3.2/README
/usr/share/doc/openjade-1.3.2/mif.htm
/usr/share/doc/openjade-1.3.2/COPYING
/usr/share/doc/openjade-1.3.2/xmlfo.htm
/usr/share/doc/openjade-1.3.2/images
/usr/share/doc/openjade-1.3.2/images/top-of-page.gif
/usr/share/doc/openjade-1.3.2/images/background.gif
/usr/share/doc/openjade-1.3.2/images/dsssltitle.gif
/usr/share/doc/openjade-1.3.2/images/space.gif
/usr/share/doc/openjade-1.3.2/index.htm
/usr/share/doc/openjade-1.3.2/copying.txt
/usr/share/doc/openjade-1.3.2/contributors.htm
/usr/share/doc/openjade-1.3.2/dsssl2.htm
/usr/share/doc/openjade-1.3.2/VERSION
/usr/share/doc/openjade-1.3.2/transform.htm
/usr/share/doc/openjade-1.3.2/README.jadetex
/usr/share/doc/openjade-1.3.2/tex.htm
/usr/local/lib/pkgconfig/libopenjp2.pc
/usr/local/lib/libopenjp2.so
/usr/local/lib/openjpeg-2.1
/usr/local/lib/openjpeg-2.1/OpenJPEGTargets-noconfig.cmake
/usr/local/lib/openjpeg-2.1/OpenJPEGTargets.cmake
/usr/local/lib/openjpeg-2.1/OpenJPEGConfig.cmake
/usr/local/lib/libopenjp2.so.7
/usr/local/lib/libopenjp2.so.2.1.0
/usr/local/include/openjpeg-2.1
/usr/local/include/openjpeg-2.1/opj_stdint.h
/usr/local/include/openjpeg-2.1/opj_config.h
/usr/local/include/openjpeg-2.1/openjpeg.h
/usr/lib64/libopenjpeg.so.2
/usr/lib64/libopenjpeg.so.2.1.3.0
/usr/lib/libopenjp2.so.2.0.0
/usr/lib/jvm-private/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64
/usr/lib/jvm-private/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jce
/usr/lib/jvm-private/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jce/vanilla
/usr/lib/jvm-exports/jre-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-rmi-1.8.0.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-cos-1.8.0.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jce-1.8.0.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-cos-1.8.0.45.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/sasl-1.8.0.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jaas-1.8.0.45.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-rmi.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-1.8.0.45.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jdbc-stdext-1.8.0.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-rmi-1.8.0.45.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-cos.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-ldap-1.8.0.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jsse.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jce.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-ldap.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jce-1.8.0.45.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-1.8.0.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi-ldap-1.8.0.45.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jndi.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jdbc-stdext.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jsse-1.8.0.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/sasl-1.8.0.45.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jaas-1.8.0.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jaas.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jdbc-stdext-1.8.0.45.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jdbc-stdext-3.0.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jsse-1.8.0.45.jar
/usr/lib/jvm-exports/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/sasl.jar
/usr/lib/jvm-exports/jre-openjdk
/usr/lib/jvm/jre-1.8.0-openjdk
/usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/calendars.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/content-types.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/charsets.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/management-agent.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjawt.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libattach.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libsctp.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libawt.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjavalcms.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libj2pkcs11.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjsoundalsa.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/jvm.cfg
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libawt_headless.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libnio.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/server
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/server/Xusage.txt
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/server/classes.jsa
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/server/libjvm.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/server/libjsig.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libnet.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjaas_unix.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libsaproc.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjsound.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libinstrument.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libsplashscreen.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libdt_socket.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libj2pcsc.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libzip.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libhprof.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libmanagement.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libmlib_image.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/client
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/jli
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/jli/libjli.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjdwp.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjsdt.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjsig.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjavajpeg.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libnpt.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libunpack.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libfontmanager.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjava_crw_demo.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libawt_xawt.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libverify.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libj2gss.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/amd64/libjava.so
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/hijrah-config-umalqura.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/logging.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/applet
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/cmm
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/cmm/LINEAR_RGB.pf
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/cmm/PYCC.pf
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/cmm/GRAY.pf
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/cmm/sRGB.pf
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/cmm/CIEXYZ.pf
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/rt.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/net.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/meta-index
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/classlist
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/management
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/management/jmxremote.password.template
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/management/snmp.acl.template
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/management/management.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/management/jmxremote.access
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/resources.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/sound.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/security
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/security/US_export_policy.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/security/java.security
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/security/local_policy.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/security/blacklisted.certs
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/security/nss.cfg
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/security/cacerts
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/security/java.policy
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/ext
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/ext/sunpkcs11.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/ext/meta-index
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/ext/sunjce_provider.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/ext/dnsns.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/ext/zipfs.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/ext/cldrdata.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/ext/sunec.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/ext/localedata.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/ext/nashorn.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/jsse.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/currency.data
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/jce.jar
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/images
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/images/cursors
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/images/cursors/motif_CopyNoDrop32x32.gif
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/images/cursors/cursors.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/images/cursors/motif_MoveDrop32x32.gif
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/images/cursors/motif_LinkNoDrop32x32.gif
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/images/cursors/motif_LinkDrop32x32.gif
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/images/cursors/invalid32x32.gif
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/images/cursors/motif_CopyDrop32x32.gif
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/images/cursors/motif_MoveNoDrop32x32.gif
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/audio
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/audio/default.sf2
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/jexec
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/psfontj2d.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/jvm.hprof.txt
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/tz.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/tzdb.dat
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/flavormap.properties
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/lib/psfont.properties.ja
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/pack200
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/java
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/unpack200
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/rmid
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/rmiregistry
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/jjs
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/tnameserv
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/keytool
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/servertool
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/orbd
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64/jre/bin/policytool
/usr/lib/jvm/jre-openjdk
/usr/lib/libopenjp2.so.6
/usr/bin/openjade

**Comment by danigm** [comment]
https://poppler.freedesktop.org/

**Comment by WillCallahan** [comment]
@danigm You did not provide any meaningful support with your comment. This issue continue to persist today.

**Comment by danigm** [comment]
> @danigm You did not provide any meaningful support with your comment. This issue continue to persist today.

This is not the project repository, just a personal fork that I created to work on an feature, please, go to the project official repository to report any issue with the current version: https://gitlab.freedesktop.org/poppler/poppler/
