### ISSUE TITLE
width set to 0 for vertical text

### ISSUE THREAD

**Issue by comhon-project** [danigm/poppler#2]
I'm trying to transform a pdf to html file using 'pdftohtml' that contain japanese langage.
Everything is fine with horizontal text but each generated div for vertical text has width set to 0.

I tried to fix this and I have found this in following function ```GfxCIDFont::getNextChar()``` :  
```
...
  // vertical
  } else {
    w = 0;
...
```
and width doesn't seem to be updated later. So I have tried to do like in horizontal mode : 
```
...
  // vertical
  } else {
    w =getWidth(cid);
...
```
the result is good, all my divs have a width. Is it the right way ? and Do I have to do pull request ?

**Comment by danigm** [comment]
This is no the official poppler repository, this is just my branch where I've uploaded some changes. The poppler project is in freedesktop: https://poppler.freedesktop.org/

You should ask there.
